account_id = "78ffaadfca16a9a0dc6122c827e86802"
name = "cloudfare"
type = "webpack"
webpack_config = "webpack.config.js"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket="./public",entry-point="worker-site"}
compatibility_date = "2022-07-24"
